// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOluuf2F1X2eJRC6g9dVRzfLvzg28wiUw',
    appId: '1:145242219808:web:d0380d861c4b40d119e345',
    messagingSenderId: '145242219808',
    projectId: 'checkit-bc3f4',
    authDomain: 'checkit-bc3f4.firebaseapp.com',
    storageBucket: 'checkit-bc3f4.firebasestorage.app',
    measurementId: 'G-EZW758W00V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeLhenmlkgfsWUIp2UKu2goP1uHD_6TSA',
    appId: '1:145242219808:android:0fa56c4e8797c1ae19e345',
    messagingSenderId: '145242219808',
    projectId: 'checkit-bc3f4',
    storageBucket: 'checkit-bc3f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnXRWn8l8NX-o4U93LntC9g8GrCUPxO4I',
    appId: '1:145242219808:ios:b77f326cd8f2cb4c19e345',
    messagingSenderId: '145242219808',
    projectId: 'checkit-bc3f4',
    storageBucket: 'checkit-bc3f4.firebasestorage.app',
    iosBundleId: 'com.abishek.checkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnXRWn8l8NX-o4U93LntC9g8GrCUPxO4I',
    appId: '1:145242219808:ios:b77f326cd8f2cb4c19e345',
    messagingSenderId: '145242219808',
    projectId: 'checkit-bc3f4',
    storageBucket: 'checkit-bc3f4.firebasestorage.app',
    iosBundleId: 'com.abishek.checkit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOluuf2F1X2eJRC6g9dVRzfLvzg28wiUw',
    appId: '1:145242219808:web:f30ddbabc4aa0b1819e345',
    messagingSenderId: '145242219808',
    projectId: 'checkit-bc3f4',
    authDomain: 'checkit-bc3f4.firebaseapp.com',
    storageBucket: 'checkit-bc3f4.firebasestorage.app',
    measurementId: 'G-RMK2DF7MRP',
  );
}
